server:
  port: 8082
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  application:
    name: SpringBoot
  datasource:
    password: root
    url: jdbc:mysql:///db_goblins?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  data:
    redis:
      host: localhost
      port: 6379
      password: ""
      database: 0
      timeout: 5000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gbl.mybatis.entity
  configuration:
    map-underscore-to-camel-case: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:mapper/**/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 日志配置
logging:
  level:
    root: INFO
    com.gbl: DEBUG
  file:
    name: /your_path/springboot.log

video:
  upload:
    path: KuYunClass